# Generated by Django 4.1.3 on 2022-11-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Post", new_name="Product",),
    ]
