# Generated by Django 4.1.3 on 2022-11-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0002_rename_post_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
