# Generated by Django 4.1.3 on 2022-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0007_tag_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product", name="page", field=models.IntegerField(null=True),
        ),
    ]
