# Generated by Django 4.1.3 on 2022-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0008_product_date_product_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="address",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="publisher",
            name="phone",
            field=models.CharField(default=3333, max_length=20),
            preserve_default=False,
        ),
    ]
