# Generated by Django 4.1.3 on 2022-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0009_publisher_address_publisher_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher", name="address", field=models.TextField(),
        ),
    ]
