# Generated by Django 4.1.3 on 2022-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0010_alter_publisher_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="author",
            field=models.CharField(default=333, max_length=10),
            preserve_default=False,
        ),
    ]
