# Generated by Django 4.1.3 on 2022-11-06 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product_item", "0011_publisher_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher", old_name="name", new_name="publisher",
        ),
    ]
